### PR TITLE
Add cross-domain permissions to Firefox manifest

### PR DESCRIPTION
**Pull request by ckarlof**
Otherwise it don't work!

### CODE REVIEW

**Comment by ckarlof** [comment]
It has the dev URL right in there. We'll need to figure out a way of building these in a environment specific way.

**Comment by pdehaan** [comment]
Totally, since I think this is now the _third_ place where we're hardcoding the domain (the other two being [/chrome/main.js:1](https://github.com/mozilla/chronicle-addon/blob/e15cf169571b4db2b4a7700f90fc7e417ad013cf/chrome/main.js#L1) and [/data/content_scripts/visit.js:1](https://github.com/mozilla/chronicle-addon/blob/e15cf169571b4db2b4a7700f90fc7e417ad013cf/data/content_scripts/visit.js#L1)).

**Comment by ckarlof** [comment]
> Totally, since I think this is now the third place where we're hardcoding the domain (the other two being /chrome/main.js:1 and /data/content_scripts/visit.js:1).

#7 makes this better, but since this origin is required in the manifest, I don't immediately see any way to make this really nice. We could list all the origins that chronicle would possibly use in all environments here.

**Comment by jaredhirsch** [comment]
@ckarlof maybe the answer is to have different addons for different environments. might be painful for us (chronicle devs), but for normal people, it's a perfectly fine solution. anyway, to be continued.

**Pull request merged**
